name: 4127_IIAVSR_mix_precision_REDS_600K_N1
model_type: RecurrentMixPrecisionRTModel
scale: 4
num_gpu: 1  # official: 8 GPUs
manual_seed: 0
find_unused_parameters: false
use_static_graph: true
# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: REDSRecurrentDistillationDataset
    dataroot_gt: /home/mohammad/Documents/uni/deep learning/FinalProject/train_sharp/train/train_sharp
    dataroot_lq: /home/mohammad/Documents/uni/deep learning/FinalProject/train_sharp_bicubic/train/train_sharp_bicubic/X4
    meta_info_file: /home/mohammad/Documents/uni/deep learning/FinalProject/MIA-VSR/data/meta_info_REDS_GT_30.txt
    # dataroot_gt: /content/train_sharp/train/train_sharp
    # dataroot_lq: /content/train_sharp_bi/train/train_sharp_bicubic/X4
    # meta_info_file: /content/MIA-VSR/data/meta_info_REDS_GT_30.txt
    val_partition: REDS4  # set to 'official' when use the official validation partition
    # val_partition: 'official'  # set to 'official' when use the official validation partition
    test_mode: False
    io_backend:
      type: disk

    num_frame: 8
    gt_size: 128
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    pin_memory: true

    # feature_hdf5_path: '/home/mohammad/Documents/uni/deep learning/FinalProject/MIA-VSR/data/anchor_maps_teacher.h5'
    feature_hdf5_path: '/home/mohammad/Documents/uni/deep learning/FinalProject/MIA-VSR/data/anchor_maps_teacher.h5'
    kd_enabled: false

  val:
    name: REDS4
    type: VideoRecurrentTestDataset
    dataroot_gt: /content/val_sharp/val
    dataroot_lq: /content/val_sharp_bi/val/X4

    cache_data: true
    io_backend:
      type: disk

    num_frame: -1  # not needed

# network structures
network_g:
  type: IIAVSR
  mid_channels: 32
  embed_dim: 32
  depths: [4,4]
  num_heads: [4,4]
  window_size: [3, 8, 8]
  num_frames: 3
  img_size : 32
  patch_size : 1
  cpu_cache_length: 100
  is_low_res_input: True
  # spynet_path: /content/MIA-VSR/experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth
  spynet_path: /home/mohammad/Documents/uni/deep learning/FinalProject/MIA-VSR/experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~
  # resume_state: "/home/mohammad/Documents/uni/deep learning/FinalProject/MIA-VSR/experiments/2.state"
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [20000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 20000
  warmup_iter: -1  # no warm up
  fix_flow: 5000 #-1 no fix flow
  flow_lr_mul: 0.125

  # curriculum learning settings
  curriculum:
    enabled: true
    switch_iter: 300000  # Iteration to switch to the next phase
    phase2:
      gt_size: 256  # Corresponds to 64x64 LQ patches for 4x SR
      batch_size_per_gpu: 2  # Reduce batch size for larger patches to fit in memory


  # kd
  knowledge_distillation:
    enabled: false
    start_iter: 1200

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: 100
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: 200
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500